python ./selenium_impl/main.py multi --folder "F:\Download\幻造-聖杯戰爭" --desc "劇情" --tags "崩壞星穹鐵道,honkaistarrail,幻造-聖杯戰爭" --playlist "崩壞:星穹鐵道"
# python ./selenium_impl/main.py multi --folder "F:\Download\2026-08-03-虛構敘事-構事生意" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,構事生意" --playlist "崩壞:星穹鐵道-高難"
# python ./selenium_impl/main.py multi --folder "F:\2026-07-06-忘卻之庭-學院怪談" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,學院怪談" --playlist "崩壞:星穹鐵道-高難"
# python ./selenium_impl/main.py multi --folder "F:\2026-07-18-異相仲裁-塵世卷中" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,嗡鳴如笑" --playlist "崩壞:星穹鐵道-高難"
# python ./selenium_impl/main.py multi --folder "F:\Download\2026-07-20-末日幻影-兵鋒騎士-2" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,兵鋒騎士" --playlist "崩壞:星穹鐵道-高難"